# PSID Crisis Module - Final Binary Workflow

## Objective

This notebook documents the refreshed production workflow for the PSID crisis module after the client-facing refactor.

The current workflow in this notebook does five things:

1. Rebuilds the final ranked dataset from `PSID_Ranked_Questions_Katrina_Integrated.csv`.
2. Recomputes utility, burden, Ri, Pi, variable names, and deployable wording.
3. Applies the binary category model: `Generic` versus `Specific`.
4. Validates the refreshed selected module, threshold logic, and demographic interaction behavior.
5. Refreshes the ranked CSV, summary bundle, figures, questionnaire exports, and client PDFs through `build_all()` and `generate_client_documents.py`.

## Production Pipeline

```
PSID_Ranked_Questions_Katrina_Integrated.csv
    -> build_ranked_dataset() from generate_psid_artifacts.py
    -> normalized Ri thresholding (0.70) for Generic vs Specific
    -> selected module review and validation
    -> build_all() refresh for CSV, summary, dashboard, and figures
    -> generate_client_documents.py for questionnaires, codebook, and final report PDFs
```

**Version**: Final binary workflow
**Last Updated**: 2026-04-05

In [19]:
import importlib
import json
import pandas as pd
from IPython.display import display

import PSID_NLP_Crisis_Module_Structure as structure
import generate_psid_artifacts as artifacts
import generate_client_documents as client_documents

structure = importlib.reload(structure)
artifacts = importlib.reload(artifacts)
client_documents = importlib.reload(client_documents)

ROOT = artifacts.ROOT
RAW_CSV_PATH = artifacts.RAW_CSV_PATH
CSV_PATH = artifacts.CSV_PATH
SUMMARY_PATH = artifacts.SUMMARY_PATH
DASHBOARD_DATA_PATH = artifacts.DASHBOARD_DATA_PATH
FIG_TOP = artifacts.FIG_TOP
FIG_TOGGLE = artifacts.FIG_TOGGLE
FIG_UTILITY = artifacts.FIG_UTILITY
FIG_HEATMAP = artifacts.FIG_HEATMAP
FIG_TIME = artifacts.FIG_TIME

MASTER_XLSX = client_documents.MASTER_XLSX
DEPLOYABLE_PDF = client_documents.DEPLOYABLE_PDF
CODEBOOK_PDF = client_documents.CODEBOOK_PDF
REPORT_PDF = client_documents.REPORT_PDF

build_all = artifacts.build_all
build_ranked_dataset = artifacts.build_ranked_dataset
load_dataset = artifacts.load_dataset
build_summary = artifacts.build_summary
GENERIC_LABEL = artifacts.GENERIC_LABEL
SPECIFIC_LABEL = artifacts.SPECIFIC_LABEL
RI_BINARY_THRESHOLD = artifacts.RI_BINARY_THRESHOLD

pd.set_option("display.max_colwidth", 160)
pd.set_option("display.max_columns", 24)

print("Environment ready for the final binary workflow")
print(f"Raw source CSV: {RAW_CSV_PATH.relative_to(ROOT)}")
print(f"Final ranked CSV: {CSV_PATH.relative_to(ROOT)}")
print(f"Binary Generic threshold: ri_threshold_score >= {RI_BINARY_THRESHOLD:.2f}")

Environment ready for the final binary workflow
Raw source CSV: data/PSID_Ranked_Questions_Katrina_Integrated.csv
Final ranked CSV: data/PSID_Ranked_Questions_Final.csv
Binary Generic threshold: ri_threshold_score >= 0.70

In [2]:
df = build_ranked_dataset()
selected_df = df[df["selected"]].copy()

summary_view = {
    "rows": int(len(df)),
    "selected_rows": int(len(selected_df)),
    "selected_minutes": round(float(selected_df["minutes"].sum()), 2),
    "all_minutes": round(float(df["minutes"].sum()), 2),
    "avg_ri": round(float(df["Ri"].mean()), 3),
    "max_ri": round(float(df["Ri"].max()), 3),
    "avg_pi": round(float(df["Pi"].mean()), 3),
    "max_pi": round(float(df["Pi"].max()), 3),
    "generic_rows": int((df["toggle_category"] == GENERIC_LABEL).sum()),
    "specific_rows": int((df["toggle_category"] == SPECIFIC_LABEL).sum()),
}

display(pd.DataFrame([summary_view]))

,rows,selected_rows,selected_minutes,all_minutes,avg_ri,max_ri,avg_pi,max_pi,generic_rows,specific_rows
0,52,28,29.98,68.6,2.201,5.667,2.561,7.86,3,49

In [3]:
preview_columns = [
    "variable_name",
    "question_text",
    "recommended_wording",
    "source",
    "toggle_category",
    "historical_toggle_category",
    "ri_threshold_score",
    "Ui",
    "Bi",
    "Ri",
    "Pi",
    "selected",
    "word_count",
    "minutes",
    "constructs",
]

display(df[preview_columns].head(12))

,variable_name,question_text,recommended_wording,source,toggle_category,historical_toggle_category,ri_threshold_score,Ui,Bi,Ri,Pi,selected,word_count,minutes,constructs
0,SPC_HOME_DAMAGED_DESTROYED_DISASTER,Was your home damaged or destroyed by Katrina or Rita?,Was your home damaged or destroyed by the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,0.377813,2.65,1.0,2.650000,2.265634,True,10,1.166667,"[Housing / Shelter, Trauma / Health]"
1,SPC_BUSINESS_DAMAGED_DESTROYED_DISASTER,Was your business damaged or destroyed by Katrina or Rita?,Was your business damaged or destroyed by the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,0.511875,3.30,1.0,3.300000,2.961770,True,10,1.166667,"[Economic / Income, Trauma / Health]"
2,GEN_EXPERIENCED_FINANCIAL_DIFFICULTIES_C,Any financial difficulties,Have you experienced any financial difficulties because of the crisis?,COVID-19,Generic,Generic Core,1.000000,1.70,0.3,5.666667,7.187001,True,3,0.350000,[Financial Coping]
3,GEN_LOSE_EARNINGS_PANDEMIC,Lost earnings because of the pandemic,Did you lose earnings because of the pandemic?,COVID-19,Generic,Toggle: Pandemic / Disaster,1.000000,3.40,0.6,5.666667,7.860359,True,6,0.700000,"[Economic / Income, Trauma / Health]"
4,SPC_WORK_ENTIRELY_HOME_DURING,Only work from home,Did you work entirely from home during the crisis?,COVID-19,Specific,Toggle: Pandemic / Disaster,0.553125,1.40,0.4,3.500000,3.957207,True,4,0.466667,[Employment]
5,SPC_STOPPED_WORK_CRISIS,stopped this work?,Have you stopped this work because of the crisis?,Govt Shutdown Income,Specific,Generic Core,0.553125,1.40,0.4,3.500000,4.134274,True,4,0.466667,[Employment]
6,SPC_WAGES_SALARY_PAYMENTS_JOB,Were/Was there any wages or salarys from this job/these jobs?,Were there any wages or salary payments from this job during the crisis period?,Govt Shutdown Income,Specific,Generic Core,0.393750,3.00,1.1,2.727273,4.134001,True,10,1.166667,"[Economic / Income, Employment]"
7,SPC_ANYONE_IMMEDIATE_FAMILY_KILLED,Was anyone in your immediate family killed as a result of Katrina or Rita?,Was anyone in your immediate family killed as a result of the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,0.267548,2.75,1.3,2.115385,2.059919,True,13,1.516667,[Trauma / Health]
8,SPC_EXPERIENCE_HURRICANE_FORCE_WINDS,Did you experience hurricane force winds at your location during Katrina or Rita?,Did you experience hurricane force winds at your location during the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,0.259615,2.70,1.3,2.076923,2.106316,True,13,1.516667,[Trauma / Health]
9,SPC_EXPERIENCE_MAJOR_FLOODING_HOME,Did you experience major flooding in your home from Katrina or Rita?,Did you experience major flooding in your home during the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,0.613281,4.55,1.2,3.791667,4.222413,True,12,1.400000,"[Housing / Shelter, Trauma / Health]"
10,GEN_RECEIVE_STIMULUS_PAYMENT_OTHER,Received stimulus payment,Did you receive a stimulus payment or other emergency government support?,COVID-19,Generic,Toggle: Pandemic / Disaster,0.793750,1.40,0.3,4.666667,6.327809,True,3,0.350000,[Government Aid]
11,SPC_PHYSICALLY_INJURED_WAY_AS,Were you physically injured in any way as a result of Katrina or Rita?,Were you physically injured in any way as a result of the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,0.418269,3.70,1.3,2.846154,2.804350,True,13,1.516667,[Trauma / Health]

## 2. Refreshed Corpus Snapshot

In [4]:
source_counts = df["source"].value_counts().rename_axis("source").reset_index(name="questions")
category_counts = df["toggle_category"].value_counts().rename_axis("toggle_category").reset_index(name="questions")
selected_timing_by_category = (
    selected_df.groupby("toggle_category", as_index=False)["minutes"]
    .sum()
    .sort_values("minutes", ascending=False)
    .rename(columns={"minutes": "selected_minutes"})
)
selected_timing_by_category["selected_minutes"] = selected_timing_by_category["selected_minutes"].round(2)

print("Source distribution")
display(source_counts)

print("Binary category distribution")
display(category_counts)

print("Selected module timing by binary category")
display(selected_timing_by_category)

Source distribution

                   source  questions
0  Hurricane Katrina 2007         37
1                COVID-19          8
2    Govt Shutdown Income          3
3   Understanding Society          3
4    Govt Shutdown Crisis          1

Binary category distribution

  toggle_category  questions
0        Specific         49
1         Generic          3

Selected module timing by binary category

  toggle_category  selected_minutes
1        Specific             28.58
0         Generic              1.40

The ranked corpus still contains 52 questions across five historical sources, but the final client-facing category model is now binary. The current `toggle_category` field stores only `Generic` or `Specific`, while `historical_toggle_category` preserves the older source-derived labels for traceability.

## 3. Threshold Logic and Top Ranked Question Review

In [5]:
raw_threshold_diagnostics = pd.DataFrame(
    [
        {"metric": "Minimum raw Ri", "value": round(float(df["Ri"].min()), 3)},
        {"metric": "Maximum raw Ri", "value": round(float(df["Ri"].max()), 3)},
        {"metric": "Rows with raw Ri >= 0.70", "value": int((df["Ri"] >= 0.70).sum())},
        {"metric": "Rows with normalized Ri >= 0.70", "value": int((df["ri_threshold_score"] >= RI_BINARY_THRESHOLD).sum())},
    ]
)

top_ranked = (
    df.sort_values(["Ri", "Pi"], ascending=[False, False])
    [[
        "variable_name",
        "recommended_wording",
        "source",
        "toggle_category",
        "historical_toggle_category",
        "ri_threshold_score",
        "Ri",
        "Pi",
        "selected",
    ]]
    .head(15)
    .reset_index(drop=True)
)

print("Threshold diagnostics")
display(raw_threshold_diagnostics)

print("Top ranked questions")
display(top_ranked)

Threshold diagnostics

                            metric   value
0                   Minimum raw Ri   0.818
1                   Maximum raw Ri   5.667
2         Rows with raw Ri >= 0.70  52.000
3  Rows with normalized Ri >= 0.70   3.000

Top ranked questions

,variable_name,recommended_wording,source,toggle_category,historical_toggle_category,ri_threshold_score,Ri,Pi,selected
0,GEN_LOSE_EARNINGS_PANDEMIC,Did you lose earnings because of the pandemic?,COVID-19,Generic,Toggle: Pandemic / Disaster,1.000000,5.666667,7.860359,True
1,GEN_EXPERIENCED_FINANCIAL_DIFFICULTIES_C,Have you experienced any financial difficulties because of the crisis?,COVID-19,Generic,Generic Core,1.000000,5.666667,7.187001,True
2,GEN_RECEIVE_STIMULUS_PAYMENT_OTHER,Did you receive a stimulus payment or other emergency government support?,COVID-19,Generic,Toggle: Pandemic / Disaster,0.793750,4.666667,6.327809,True
3,SPC_WORKING_JOB_CONSIDERED_ESSENTIAL,Were you working in a job that was considered essential during the crisis?,COVID-19,Specific,Generic Core,0.656250,4.000000,5.222804,True
4,SPC_EXPERIENCE_MAJOR_FLOODING_HOME,Did you experience major flooding in your home during the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,0.613281,3.791667,4.222413,True
5,SPC_STOPPED_WORKING_BUSINESS_CRISIS,Have you stopped working at this business because of the crisis?,Govt Shutdown Income,Specific,Generic Core,0.604688,3.750000,5.177179,True
6,SPC_HOUSEHOLD_MANAGE_FINANCIAL_DIFFICULT,How did your household manage financial difficulties caused by the shutdown or crisis?,Govt Shutdown Crisis,Specific,Toggle: Financial Crisis,0.598242,3.718750,4.591916,True
7,SPC_RECEIVE_PAYCHECK_PROTECTION_OTHER,Did you receive paycheck protection or other emergency business support?,COVID-19,Specific,Toggle: Pandemic / Disaster,0.553125,3.500000,5.212261,True
8,SPC_RECEIVE_STIMULUS_PAYMENT_OTHER,Did you receive a stimulus payment or other emergency government support?,COVID-19,Specific,Toggle: Pandemic / Disaster,0.553125,3.500000,4.465856,True
9,SPC_STOPPED_WORK_CRISIS,Have you stopped this work because of the crisis?,Govt Shutdown Income,Specific,Generic Core,0.553125,3.500000,4.134274,True
10,SPC_WORK_ENTIRELY_HOME_DURING,Did you work entirely from home during the crisis?,COVID-19,Specific,Toggle: Pandemic / Disaster,0.553125,3.500000,3.957207,True
11,SPC_BUSINESS_DAMAGED_DESTROYED_DISASTER,Was your business damaged or destroyed by the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,0.511875,3.300000,2.961770,True
12,SPC_EVACUATE_HOME_DISASTER_HIT,Did you evacuate from your home before the disaster hit?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,0.496875,3.227273,3.529990,True
13,SPC_DISASTER_CAUSE_LOSE_JOB,Did the disaster cause you to lose your job?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,0.491250,3.200000,3.707594,True
14,SPC_PHYSICALLY_INJURED_WAY_AS,Were you physically injured in any way as a result of the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,0.418269,2.846154,2.804350,True

A direct raw `Ri >= 0.70` rule would classify 51 of the 52 rows as `Generic`, so the binary split shown here is produced from the normalized `ri_threshold_score`. That preserves the requested threshold while keeping the category model interpretable.

## 4. Selected Module Composition

In [6]:
selected_breakdown = (
    selected_df.groupby(["toggle_category", "source"], as_index=False)
    .agg(
        selected_questions=("question_text", "count"),
        total_minutes=("minutes", "sum"),
        avg_ri=("Ri", "mean"),
        avg_pi=("Pi", "mean"),
    )
    .sort_values(["toggle_category", "total_minutes"], ascending=[True, False])
)

selected_breakdown["total_minutes"] = selected_breakdown["total_minutes"].round(2)
selected_breakdown["avg_ri"] = selected_breakdown["avg_ri"].round(3)
selected_breakdown["avg_pi"] = selected_breakdown["avg_pi"].round(3)

display(selected_breakdown)

,toggle_category,source,selected_questions,total_minutes,avg_ri,avg_pi
0,Generic,COVID-19,3,1.40,5.333,7.125
4,Specific,Hurricane Katrina 2007,14,20.30,2.617,2.769
1,Specific,COVID-19,5,2.92,3.364,4.393
3,Specific,Govt Shutdown Income,3,2.33,3.326,4.482
2,Specific,Govt Shutdown Crisis,1,1.87,3.719,4.592
5,Specific,Understanding Society,2,1.17,1.447,2.329

The selected module remains just under the 30-minute ceiling at 29.98 minutes. Under the refreshed binary model, only three rows qualify as `Generic`, while the remaining selected rows stay in `Specific` and preserve the richer disaster, pandemic, and shutdown evidence base.

## 5. Construct Coverage and Demographic Interaction Notes

In [7]:
construct_counts = (
    selected_df["constructs"]
    .explode()
    .dropna()
    .value_counts()
    .rename_axis("construct")
    .reset_index(name="selected_questions")
)

interaction_summary = (
    df.assign(
        has_demographics=df["constructs"].fillna("").astype(str).str.contains("Demographics"),
        has_non_demographic=df["constructs"].fillna("").astype(str).apply(
            lambda text: any(
                term in text
                for term in [
                    "Economic / Income",
                    "Employment",
                    "Financial Coping",
                    "Housing / Shelter",
                    "Government Aid",
                    "Trauma / Health",
                ]
            )
        ),
    )
    .groupby(["has_demographics", "has_non_demographic"], as_index=False)
    .agg(rows=("question_text", "count"), avg_ri=("Ri", "mean"), avg_pi=("Pi", "mean"))
)
interaction_summary["avg_ri"] = interaction_summary["avg_ri"].round(3)
interaction_summary["avg_pi"] = interaction_summary["avg_pi"].round(3)

print("Selected construct coverage")
display(construct_counts)

print("Demographic interaction summary")
display(interaction_summary)

Selected construct coverage

           construct  selected_questions
0    Trauma / Health                  15
1         Employment                   7
2  Housing / Shelter                   6
3     Government Aid                   5
4  Economic / Income                   4
5   Financial Coping                   2
6       Demographics                   2

Demographic interaction summary

   has_demographics  has_non_demographic  rows  avg_ri  avg_pi
0             False                 True    49   2.253   2.584
1              True                False     3   1.354   2.189

The selected construct profile is still led by trauma, employment, housing, and aid content. The interaction summary also makes the demographic effect clear: demographic-only rows remain useful for traceability, but they carry lower average Ri and Pi than non-demographic crisis items, which is why they fall out of the deployable questionnaire.

## 6. Stakeholder Deliverables

In [22]:
deliverable_paths = [
    ("Master questionnaire spreadsheet", MASTER_XLSX),
    ("Deployable questionnaire PDF", DEPLOYABLE_PDF),
    ("Technical codebook PDF", CODEBOOK_PDF),
    ("Final report PDF", REPORT_PDF),
    ("Ranked CSV", CSV_PATH),
    ("Summary JSON", SUMMARY_PATH),
]

deliverables = pd.DataFrame(
    [
        {
            "deliverable": label,
            "file": str(path.relative_to(ROOT)),
            "exists": path.exists(),
        }
        for label, path in deliverable_paths
    ]
)

display(deliverables)

,deliverable,file,exists
0,Master questionnaire spreadsheet,deliverables/Master_Questionnaire.xlsx,True
1,Deployable questionnaire PDF,deliverables/Deployable_Questionnaire.pdf,True
2,Technical codebook PDF,deliverables/Codebook.pdf,True
3,Final report PDF,deliverables/Final_Report.pdf,True
4,Ranked CSV,data/PSID_Ranked_Questions_Final.csv,True
5,Summary JSON,data/psid_artifact_summary.json,True

The notebook now points to the same ranked CSV, summary JSON, figures, spreadsheet, and PDFs used for the client package, with live outputs grouped under `data/`, `figures/`, and `deliverables/`.

## 7. Figure Outputs and Supporting Bundles

In [23]:
figure_paths = [FIG_TOP, FIG_TOGGLE, FIG_UTILITY, FIG_HEATMAP, FIG_TIME]
figure_status = pd.DataFrame(
    [
        {
            "figure": path.name,
            "exists": path.exists(),
            "size_kb": round(path.stat().st_size / 1024, 1) if path.exists() else None,
        }
        for path in figure_paths
    ]
)

display(figure_status)

artifact_summary = json.loads(SUMMARY_PATH.read_text())
display(pd.DataFrame([artifact_summary]))

                         figure  exists  size_kb
0  fig_top_ranked_questions.png    True    162.7
1     fig_toggle_comparison.png    True     68.9
2     fig_utility_vs_burden.png    True     97.9
3     fig_construct_heatmap.png    True     98.4
4           fig_time_budget.png    True     43.8

,rows,selected_rows,selected_minutes,all_minutes,toggle_counts,selected_toggle_counts,source_counts,selected_source_counts,construct_counts,avg_ri,max_ri,avg_pi,max_pi,recommended_generic_count,recommended_specific_count
0,52,28,29.98,68.6,"{'Specific': 49, 'Generic': 3}","{'Specific': 25, 'Generic': 3}","{'Hurricane Katrina 2007': 37, 'COVID-19': 8, 'Govt Shutdown Income': 3, 'Understanding Society': 3, 'Govt Shutdown Crisis': 1}","{'Hurricane Katrina 2007': 14, 'COVID-19': 8, 'Govt Shutdown Income': 3, 'Understanding Society': 2, 'Govt Shutdown Crisis': 1}","{'Trauma / Health': 15, 'Employment': 7, 'Housing / Shelter': 6, 'Government Aid': 5, 'Economic / Income': 4, 'Financial Coping': 2, 'Demographics': 2}",2.201,5.667,2.561,7.86,6,8

The figure files are written under `figures/` and the scored outputs under `data/`, which keeps the notebook aligned with the maintained client package while older demos, aliases, and legacy web artifacts stay archived.

## 8. Selected Question Inspection

In [10]:
selected_df[
    [
        "variable_name",
        "recommended_wording",
        "source",
        "toggle_category",
        "historical_toggle_category",
        "Ri",
        "Pi",
        "minutes",
    ]
]\
    .sort_values(["toggle_category", "Ri"], ascending=[True, False])\
    .reset_index(drop=True)

,variable_name,recommended_wording,source,toggle_category,historical_toggle_category,Ri,Pi,minutes
0,GEN_EXPERIENCED_FINANCIAL_DIFFICULTIES_C,Have you experienced any financial difficulties because of the crisis?,COVID-19,Generic,Generic Core,5.666667,7.187001,0.350000
1,GEN_LOSE_EARNINGS_PANDEMIC,Did you lose earnings because of the pandemic?,COVID-19,Generic,Toggle: Pandemic / Disaster,5.666667,7.860359,0.700000
2,GEN_RECEIVE_STIMULUS_PAYMENT_OTHER,Did you receive a stimulus payment or other emergency government support?,COVID-19,Generic,Toggle: Pandemic / Disaster,4.666667,6.327809,0.350000
3,SPC_WORKING_JOB_CONSIDERED_ESSENTIAL,Were you working in a job that was considered essential during the crisis?,COVID-19,Specific,Generic Core,4.000000,5.222804,1.050000
4,SPC_EXPERIENCE_MAJOR_FLOODING_HOME,Did you experience major flooding in your home during the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,3.791667,4.222413,1.400000
5,SPC_STOPPED_WORKING_BUSINESS_CRISIS,Have you stopped working at this business because of the crisis?,Govt Shutdown Income,Specific,Generic Core,3.750000,5.177179,0.700000
6,SPC_HOUSEHOLD_MANAGE_FINANCIAL_DIFFICULT,How did your household manage financial difficulties caused by the shutdown or crisis?,Govt Shutdown Crisis,Specific,Toggle: Financial Crisis,3.718750,4.591916,1.866667
7,SPC_WORK_ENTIRELY_HOME_DURING,Did you work entirely from home during the crisis?,COVID-19,Specific,Toggle: Pandemic / Disaster,3.500000,3.957207,0.466667
8,SPC_STOPPED_WORK_CRISIS,Have you stopped this work because of the crisis?,Govt Shutdown Income,Specific,Generic Core,3.500000,4.134274,0.466667
9,SPC_RECEIVE_PAYCHECK_PROTECTION_OTHER,Did you receive paycheck protection or other emergency business support?,COVID-19,Specific,Toggle: Pandemic / Disaster,3.500000,5.212261,0.233333
10,SPC_RECEIVE_STIMULUS_PAYMENT_OTHER,Did you receive a stimulus payment or other emergency government support?,COVID-19,Specific,Toggle: Pandemic / Disaster,3.500000,4.465856,0.233333
11,SPC_BUSINESS_DAMAGED_DESTROYED_DISASTER,Was your business damaged or destroyed by the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,3.300000,2.961770,1.166667
12,SPC_EVACUATE_HOME_DISASTER_HIT,Did you evacuate from your home before the disaster hit?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,3.227273,3.529990,1.283333
13,SPC_DISASTER_CAUSE_LOSE_JOB,Did the disaster cause you to lose your job?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,3.200000,3.707594,1.166667
14,SPC_PHYSICALLY_INJURED_WAY_AS,Were you physically injured in any way as a result of the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,2.846154,2.804350,1.516667
15,SPC_SEVERE_DAMAGE_HOME_DURING,How severe was the damage to your home during the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,2.769231,3.168617,1.516667
16,SPC_WAGES_SALARY_PAYMENTS_JOB,Were there any wages or salary payments from this job during the crisis period?,Govt Shutdown Income,Specific,Generic Core,2.727273,4.134001,1.166667
17,SPC_HOME_DAMAGED_DESTROYED_DISASTER,Was your home damaged or destroyed by the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,2.650000,2.265634,1.166667
18,SPC_LONG_STAY_TEMPORARY_HOUSING,How long did you stay in temporary housing after the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,2.454545,3.090331,1.283333
19,SPC_AFRAID_DURING_DISASTER_MIGHT,How afraid were you during the disaster that you might be seriously injured or killed?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,2.447368,2.584434,1.866667
20,SPC_LAID_OFF_FURLOUGHED_PANDEMIC,Were you laid off or furloughed because of the pandemic?,COVID-19,Specific,Toggle: Pandemic / Disaster,2.318182,3.106251,0.933333
21,SPC_ANYONE_IMMEDIATE_FAMILY_KILLED,Was anyone in your immediate family killed as a result of the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,2.115385,2.059919,1.516667
22,SPC_DISPLACED_PLACE_LIVING_DISASTER,Were you displaced from the place you were living because of the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,2.115385,2.643381,1.516667
23,SPC_EXPERIENCE_HURRICANE_FORCE_WINDS,Did you experience hurricane force winds at your location during the disaster?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,2.076923,2.106316,1.516667
24,SPC_DISASTER_OFTEN_DISTURBING_MEMORIES,"Since the disaster, how often have you had disturbing memories or images about what happened?",Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,1.825000,1.588314,2.100000
25,SPC_RECEIVE_HELP_FEMA_FEDERAL,Did you receive any help from FEMA Federal Emergency Management Agency?,Hurricane Katrina 2007,Specific,Toggle: Pandemic / Disaster,1.818182,2.026953,1.283333
26,SPC_AGE_YEARS,What is your age in years?,Understanding Society,Specific,Generic Core,1.666667,2.725444,0.350000
27,SPC_DESCRIBE_SEX_GENDER,How do you describe your sex or gender?,Understanding Society,Specific,Generic Core,1.227273,1.933282,0.816667

In [11]:
selected_df.nlargest(10, "Ri")[
    ["variable_name", "recommended_wording", "source", "toggle_category", "Ri", "Pi", "minutes"]
]\
    .reset_index(drop=True)

,variable_name,recommended_wording,source,toggle_category,Ri,Pi,minutes
0,GEN_EXPERIENCED_FINANCIAL_DIFFICULTIES_C,Have you experienced any financial difficulties because of the crisis?,COVID-19,Generic,5.666667,7.187001,0.350000
1,GEN_LOSE_EARNINGS_PANDEMIC,Did you lose earnings because of the pandemic?,COVID-19,Generic,5.666667,7.860359,0.700000
2,GEN_RECEIVE_STIMULUS_PAYMENT_OTHER,Did you receive a stimulus payment or other emergency government support?,COVID-19,Generic,4.666667,6.327809,0.350000
3,SPC_WORKING_JOB_CONSIDERED_ESSENTIAL,Were you working in a job that was considered essential during the crisis?,COVID-19,Specific,4.000000,5.222804,1.050000
4,SPC_EXPERIENCE_MAJOR_FLOODING_HOME,Did you experience major flooding in your home during the disaster?,Hurricane Katrina 2007,Specific,3.791667,4.222413,1.400000
5,SPC_STOPPED_WORKING_BUSINESS_CRISIS,Have you stopped working at this business because of the crisis?,Govt Shutdown Income,Specific,3.750000,5.177179,0.700000
6,SPC_HOUSEHOLD_MANAGE_FINANCIAL_DIFFICULT,How did your household manage financial difficulties caused by the shutdown or crisis?,Govt Shutdown Crisis,Specific,3.718750,4.591916,1.866667
7,SPC_WORK_ENTIRELY_HOME_DURING,Did you work entirely from home during the crisis?,COVID-19,Specific,3.500000,3.957207,0.466667
8,SPC_STOPPED_WORK_CRISIS,Have you stopped this work because of the crisis?,Govt Shutdown Income,Specific,3.500000,4.134274,0.466667
9,SPC_RECEIVE_PAYCHECK_PROTECTION_OTHER,Did you receive paycheck protection or other emergency business support?,COVID-19,Specific,3.500000,5.212261,0.233333

In [12]:
pd.crosstab(
    selected_df["toggle_category"],
    selected_df["source"],
    margins=True,
    margins_name="total",
)

source,COVID-19,Govt Shutdown Crisis,Govt Shutdown Income,Hurricane Katrina 2007,Understanding Society,total
toggle_category,,,,,,
Generic,3,0,0,0,0,3
Specific,5,1,3,14,2,25
total,8,1,3,14,2,28

In [13]:
selected_constructs = (
    selected_df[["toggle_category", "constructs"]]
    .explode("constructs")
    .dropna()
    .assign(construct=lambda frame: frame["constructs"].astype(str).str.strip())
)

pd.crosstab(
    selected_constructs["construct"],
    selected_constructs["toggle_category"],
    margins=True,
    margins_name="total",
)\
    .sort_values("total", ascending=False)\
    .head(15)

toggle_category    Generic  Specific  total
construct
total                    4        37     41
Trauma / Health          1        14     15
Employment               0         7      7
Housing / Shelter        0         6      6
Government Aid           1         4      5
Economic / Income        1         3      4
Demographics             0         2      2
Financial Coping         1         1      2

## 9. Validation Checks

These benchmarks are pinned to the refreshed binary-model rebuild so the notebook can flag accidental changes before the downstream CSV, figures, spreadsheet, and PDF deliverables are regenerated.

In [14]:
validation_checks = pd.DataFrame(
    [
        {"check": "Rows in final corpus", "value": int(len(df)), "target": 52},
        {"check": "Rows selected for module", "value": int(selected_df.shape[0]), "target": 28},
        {"check": "Selected minutes", "value": round(float(selected_df["minutes"].sum()), 2), "target": 29.98},
        {"check": "Total corpus minutes", "value": round(float(df["minutes"].sum()), 2), "target": 68.60},
        {"check": "Average Ri", "value": round(float(df["Ri"].mean()), 3), "target": 2.201},
        {"check": "Maximum Ri", "value": round(float(df["Ri"].max()), 3), "target": 5.667},
        {"check": "Average Pi", "value": round(float(df["Pi"].mean()), 3), "target": 2.561},
        {"check": "Maximum Pi", "value": round(float(df["Pi"].max()), 3), "target": 7.860},
        {"check": "Generic rows", "value": int((df["toggle_category"] == GENERIC_LABEL).sum()), "target": 3},
        {"check": "Specific rows", "value": int((df["toggle_category"] == SPECIFIC_LABEL).sum()), "target": 49},
    ]
)
validation_checks["pass"] = validation_checks["value"] == validation_checks["target"]
display(validation_checks)

                      check   value  target  pass
0      Rows in final corpus  52.000  52.000  True
1  Rows selected for module  28.000  28.000  True
2          Selected minutes  29.980  29.980  True
3      Total corpus minutes  68.600  68.600  True
4                Average Ri   2.201   2.201  True
5                Maximum Ri   5.667   5.667  True
6                Average Pi   2.561   2.561  True
7                Maximum Pi   7.860   7.860  True
8              Generic rows   3.000   3.000  True
9             Specific rows  49.000  49.000  True

## 10. Refresh the Production Artifacts

Running `build_all()` is the supported refresh path for the ranked CSV, summary bundle, dashboard data bundle, and figures written under `data/` and `figures/`. After that, `generate_client_documents.py` rebuilds the master questionnaire spreadsheet plus the deployable questionnaire, codebook, and final report PDFs under `deliverables/`.

In [20]:
updated_summary = build_all()
display(pd.DataFrame([updated_summary]))

,rows,selected_rows,selected_minutes,all_minutes,toggle_counts,selected_toggle_counts,source_counts,selected_source_counts,construct_counts,avg_ri,max_ri,avg_pi,max_pi,recommended_generic_count,recommended_specific_count
0,52,28,29.98,68.6,"{'Specific': 49, 'Generic': 3}","{'Specific': 25, 'Generic': 3}","{'Hurricane Katrina 2007': 37, 'COVID-19': 8, 'Govt Shutdown Income': 3, 'Understanding Society': 3, 'Govt Shutdown Crisis': 1}","{'Hurricane Katrina 2007': 14, 'COVID-19': 8, 'Govt Shutdown Income': 3, 'Understanding Society': 2, 'Govt Shutdown Crisis': 1}","{'Trauma / Health': 15, 'Employment': 7, 'Housing / Shelter': 6, 'Government Aid': 5, 'Economic / Income': 4, 'Financial Coping': 2, 'Demographics': 2}",2.201,5.667,2.561,7.86,6,8

## 11. Client Document Refresh

This step rebuilds the spreadsheet and PDF deliverables from the refreshed ranked dataset so the codebook, report, and questionnaire package stay aligned with the same binary-model outputs shown above.

In [21]:
import generate_client_documents as client_documents

client_documents = importlib.reload(client_documents)
client_documents.main()

{
  "master_questionnaire": "Master_Questionnaire.xlsx",
  "deployable_questionnaire": "Deployable_Questionnaire.pdf",
  "codebook_pdf": "Codebook.pdf",
  "report_pdf": "Final_Report.pdf",
  "deployable_rows": 26
}

## 12. Post-Refresh Verification

This final check reloads the written summary bundle and verifies the package files created after `build_all()` and `generate_client_documents.py`, so the notebook confirms the persisted client deliverables rather than only the in-memory dataframe state.

In [24]:
artifact_summary = json.loads(SUMMARY_PATH.read_text())
document_paths = [MASTER_XLSX, DEPLOYABLE_PDF, CODEBOOK_PDF, REPORT_PDF]
document_status = pd.DataFrame(
    [
        {"file": str(path.relative_to(ROOT)), "exists": path.exists()}
        for path in document_paths
    ]
)

display(pd.DataFrame([artifact_summary]))
display(document_status)

,rows,selected_rows,selected_minutes,all_minutes,toggle_counts,selected_toggle_counts,source_counts,selected_source_counts,construct_counts,avg_ri,max_ri,avg_pi,max_pi,recommended_generic_count,recommended_specific_count
0,52,28,29.98,68.6,"{'Specific': 49, 'Generic': 3}","{'Specific': 25, 'Generic': 3}","{'Hurricane Katrina 2007': 37, 'COVID-19': 8, 'Govt Shutdown Income': 3, 'Understanding Society': 3, 'Govt Shutdown Crisis': 1}","{'Hurricane Katrina 2007': 14, 'COVID-19': 8, 'Govt Shutdown Income': 3, 'Understanding Society': 2, 'Govt Shutdown Crisis': 1}","{'Trauma / Health': 15, 'Employment': 7, 'Housing / Shelter': 6, 'Government Aid': 5, 'Economic / Income': 4, 'Financial Coping': 2, 'Demographics': 2}",2.201,5.667,2.561,7.86,6,8

                                        file  exists
0     deliverables/Master_Questionnaire.xlsx    True
1  deliverables/Deployable_Questionnaire.pdf    True
2                  deliverables/Codebook.pdf    True
3              deliverables/Final_Report.pdf    True